#!/usr/bin/env python3
"""
Set up Career Weaver inputs in a cross-platform way.

The script intentionally handles deterministic file operations only:
- create person/job directories
- save pasted JD text or copy an existing JD file
- copy a profile photo
- create a profile draft placeholder

Agents still perform semantic extraction, matching, and resume writing.
"""

from __future__ import annotations

import argparse
import re
import shutil
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_WORKSPACE = Path.cwd()


def workspace_path(args: argparse.Namespace) -> Path:
    return Path(args.workspace).resolve()


def data_dir(args: argparse.Namespace) -> Path:
    return workspace_path(args) / "data"


def output_dir(args: argparse.Namespace) -> Path:
    return workspace_path(args) / "output"


def slugify(value: str) -> str:
    text = value.strip().lower()
    text = re.sub(r"[^a-z0-9]+", "_", text)
    return text.strip("_") or "untitled"


def person_slug(name: str) -> str:
    return slugify(name)


def ensure_person_dirs(person: str, args: argparse.Namespace) -> Path:
    person_dir = data_dir(args) / person
    (person_dir / "jds").mkdir(parents=True, exist_ok=True)
    return person_dir


def ensure_job_dirs(person: str, job: str, args: argparse.Namespace) -> Path:
    job_dir = output_dir(args) / person / "jobs" / job
    (job_dir / "deliverables").mkdir(parents=True, exist_ok=True)
    (job_dir / "debug").mkdir(parents=True, exist_ok=True)
    return job_dir


def read_stdin_text() -> str:
    if sys.stdin.isatty():
        return ""
    return sys.stdin.read()


def command_init_profile(args: argparse.Namespace) -> int:
    person = person_slug(args.name)
    person_dir = ensure_person_dirs(person, args)
    profile_path = person_dir / "profile.yaml"
    if profile_path.exists() and not args.force:
        print(f"EXISTS: {profile_path}")
        return 0

    profile_path.write_text(
        "\n".join(
            [
                "# Draft profile generated by setup_workflow.py.",
                "# Replace TODO values with facts extracted from the user's resume.",
                "",
                "profile:",
                f'  name: "{args.name}"',
                '  summary: "TODO"',
                "",
                "contact:",
                '  email: "TODO"',
                '  phone: ""',
                '  location: "TODO"',
                '  linkedin: ""',
                '  github: ""',
                "",
                "experience: []",
                "projects: []",
                "skills: []",
                "education: []",
                "certifications: []",
                "languages: []",
                "",
                "review_notes:",
                '  - "Profile is a draft. Confirm all TODO fields before generating resumes."',
                "",
            ]
        ),
        encoding="utf-8",
    )
    print(f"CREATED: {profile_path}")
    return 0


def command_save_jd(args: argparse.Namespace) -> int:
    person = person_slug(args.person)
    job = slugify(args.job)
    person_dir = ensure_person_dirs(person, args)
    job_dir = ensure_job_dirs(person, job, args)

    jd_path = person_dir / "jds" / f"{job}.txt"
    if args.file:
        source = Path(args.file)
        if not source.exists():
            print(f"ERROR: JD file not found: {source}", file=sys.stderr)
            return 1
        text = source.read_text(encoding=args.encoding)
    else:
        text = args.text or read_stdin_text()

    if not text.strip():
        print("ERROR: provide JD text with --text, --file, or stdin", file=sys.stderr)
        return 1

    jd_path.write_text(text.strip() + "\n", encoding="utf-8")
    print(f"JD: {jd_path}")
    print(f"JOB_DIR: {job_dir}")
    return 0


def command_add_photo(args: argparse.Namespace) -> int:
    person = person_slug(args.person)
    person_dir = ensure_person_dirs(person, args)
    source = Path(args.file)
    if not source.exists():
        print(f"ERROR: photo file not found: {source}", file=sys.stderr)
        return 1

    suffix = source.suffix.lower() or ".jpg"
    destination = person_dir / f"profile_photo{suffix}"
    shutil.copy2(source, destination)
    print(f"PHOTO: {destination}")
    print('Use in resume_data.json as: "photo": {"filename": "' + destination.name + '"}')
    return 0


def command_init_job(args: argparse.Namespace) -> int:
    person = person_slug(args.person)
    job = slugify(args.job)
    ensure_person_dirs(person, args)
    job_dir = ensure_job_dirs(person, job, args)
    print(f"JOB_DIR: {job_dir}")
    print(f"DEBUG_JSON: {job_dir / 'debug' / 'resume_data.json'}")
    print(f"DELIVERABLES: {job_dir / 'deliverables'}")
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Set up Career Weaver input and output files.")
    parser.add_argument(
        "--workspace",
        default=str(DEFAULT_WORKSPACE),
        help="Workspace where data/ and output/ should be created. Defaults to the current directory.",
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    init_profile = subparsers.add_parser("init-profile", help="Create a draft profile.yaml for a person.")
    init_profile.add_argument("--name", required=True, help="Person name, e.g. 'Alex Chen'.")
    init_profile.add_argument("--force", action="store_true", help="Overwrite an existing profile.yaml.")
    init_profile.set_defaults(func=command_init_profile)

    save_jd = subparsers.add_parser("save-jd", help="Save a JD from text, stdin, or an existing file.")
    save_jd.add_argument("--person", required=True, help="Person name or slug.")
    save_jd.add_argument("--job", required=True, help="Job title or slug.")
    save_jd.add_argument("--text", help="JD text. For long text, prefer stdin or --file.")
    save_jd.add_argument("--file", help="Path to an existing JD text file.")
    save_jd.add_argument("--encoding", default="utf-8", help="Encoding for --file input.")
    save_jd.set_defaults(func=command_save_jd)

    add_photo = subparsers.add_parser("add-photo", help="Copy a photo into data/{person}/.")
    add_photo.add_argument("--person", required=True, help="Person name or slug.")
    add_photo.add_argument("--file", required=True, help="Path to a photo file.")
    add_photo.set_defaults(func=command_add_photo)

    init_job = subparsers.add_parser("init-job", help="Create deliverables/ and debug/ for a job.")
    init_job.add_argument("--person", required=True, help="Person name or slug.")
    init_job.add_argument("--job", required=True, help="Job title or slug.")
    init_job.set_defaults(func=command_init_job)

    return parser


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()
    return int(args.func(args) or 0)


if __name__ == "__main__":
    raise SystemExit(main())
